version: '3.8'

services:
  # 1. Base de datos con PERSISTENCIA
  redis-db:
    image: redis:7-alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data  # Para no perder los datos si el server se reinicia
    networks:
      - predictive-net
    restart: always

  # 2. Servicio de inicialización
  setup-redis:
    build: .
    container_name: python-setup
    command: python src/setup_redis.py
    depends_on:
      redis-db:
        condition: service_started
    environment:
      - REDIS_HOST=redis-db
    # En producción eliminamos los volúmenes de código para usar los del Dockerfile
    networks:
      - predictive-net

  # 3. El Productor
  productor:
    build: .
    container_name: python-productor
    command: python src/productor.py
    depends_on:
      setup-redis:
        condition: service_completed_successfully
    environment:
      - REDIS_HOST=redis-db
      - PYTHONUNBUFFERED=1
    networks:
      - predictive-net
    restart: on-failure

  # 4. El Worker
  worker:
    build: .
    container_name: python-worker
    command: python src/worker.py worker_docker
    depends_on:
      setup-redis:
        condition: service_completed_successfully
    environment:
      - REDIS_HOST=redis-db
      - PYTHONUNBUFFERED=1
    networks:
      - predictive-net
    restart: on-failure

networks:
  predictive-net:
    driver: bridge

volumes:
  redis_data: # Definimos el volumen para Redis
