name: MLOps CI/CD Pipeline

on:
  push:
    branches: [ "ajustes_azure", "main", "test-deploy" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Ejecutar Tests con Cobertura >= 70%
        env:
          PYTHONPATH: .
        run: |
          pytest tests/ --cov=src --cov-fail-under=70

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: >
      github.ref == 'refs/heads/main' ||
      github.ref == 'refs/heads/ajustes_azure' ||
      github.ref == 'refs/heads/test-deploy' ||
      github.event_name == 'workflow_dispatch'

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Copiar archivos esenciales al servidor
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: adminuser
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          source: "src/,data/,models/,docker-compose.yml,Dockerfile,requirements.txt,.dockerignore"
          target: "/home/adminuser/predictive-maintenance-tmp"

      - name: Desplegar Microservicios en Azure (Zero-Downtime)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: adminuser
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          script: |
            rsync -a /home/adminuser/predictive-maintenance-tmp/ \
                     /home/adminuser/predictive-maintenance/

            cd /home/adminuser/predictive-maintenance

            sudo docker compose build

            sudo docker compose up -d --no-recreate --scale worker=3

            sudo docker compose restart setup-redis

            sudo docker compose wait setup-redis